name: Varis Design
favicon: null
layout_spectrum: 0.35572593030519783
typography_spectrum: 0.5807499340735376
title: Fresh design and video news from Pekka Varis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.011562552070245147
  lightness: 0.4225709750317037
  saturation: 0.7896424056962132
  rhythmicContrast: 0.36752454191446304
purpose: []
